
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mtlhardware(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW,

	//////////// SDRAM //////////
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_DQM,
	DRAM_RAS_N,
	DRAM_WE_N,

	//////////// EPCS //////////
	EPCS_ASDO,
	EPCS_DATA0,
	EPCS_DCLK,
	EPCS_NCSO,

	//////////// Accelerometer //////////
	G_SENSOR_CS_N,
	G_SENSOR_INT,
	I2C_SCLK,
	I2C_SDAT,

	//////////// 2x13 GPIO Header //////////
	PIC32_SDO1A,
   PIC32_SDI1A,
   PIC32_SCK1A,
   PIC32_CS_FPGA_N,
   PIC32_INT1,
   PIC32_INT2,
   PIC32_C1TX,
   PIC32_C1RX,
   PIC32_SCL3A,
   PIC32_SDA3A,
   PIC32_RST_FPGA_N,
   PIC32_GPIO_211,
   PIC32_GPIO_212,
	PIC32_GPIO_2_IN,

	//////////// GPIO_1, GPIO_1 connect to MTL - Multi-Touch LCD Panel //////////
	MTL_B,
	MTL_DCLK,
	MTL_G,
	MTL_HSD,
	MTL_R,
	MTL_TOUCH_I2C_SCL,
	MTL_TOUCH_I2C_SDA,
	MTL_TOUCH_INT_n,
	MTL_VSD 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;

//////////// SDRAM //////////
output		    [12:0]		DRAM_ADDR;
output		     [1:0]		DRAM_BA;
output		          		DRAM_CAS_N;
output		          		DRAM_CKE;
output		          		DRAM_CLK;
output		          		DRAM_CS_N;
inout 		    [15:0]		DRAM_DQ;
output		     [1:0]		DRAM_DQM;
output		          		DRAM_RAS_N;
output		          		DRAM_WE_N;

//////////// EPCS //////////
output		          		EPCS_ASDO;
input 		          		EPCS_DATA0;
output		          		EPCS_DCLK;
output		          		EPCS_NCSO;

//////////// Accelerometer //////////
output		          		G_SENSOR_CS_N;
input 		          		G_SENSOR_INT;
output		          		I2C_SCLK;
inout 		          		I2C_SDAT;

//////////// 2x13 GPIO Header //////////
input                       PIC32_SDO1A;
output                      PIC32_SDI1A;
input                       PIC32_SCK1A;
input                       PIC32_CS_FPGA_N;
output                      PIC32_INT1;
input                       PIC32_INT2;

input                       PIC32_C1TX;
output                      PIC32_C1RX;
inout                       PIC32_SCL3A;
inout                       PIC32_SDA3A;
input                       PIC32_RST_FPGA_N;

inout                       PIC32_GPIO_211;
inout                       PIC32_GPIO_212;
input            [2:0]      PIC32_GPIO_2_IN;

//////////// GPIO_1, GPIO_1 connect to MTL - Multi-Touch LCD Panel //////////
output		     [7:0]		MTL_B;
output		          		MTL_DCLK;
output		     [7:0]		MTL_G;
output		          		MTL_HSD;
output		     [7:0]		MTL_R;
output		          		MTL_TOUCH_I2C_SCL;
inout 		          		MTL_TOUCH_I2C_SDA;
input 		          		MTL_TOUCH_INT_n;
output		          		MTL_VSD;


//=======================================================
//  REG/WIRE declarations
//=======================================================

wire reset_n;
wire video_hs;
wire video_vs;
wire video_clk;
wire [7:0]	video_r;
wire [7:0]	video_g;
wire [7:0]	video_b;

assign {MTL_R,MTL_G,MTL_B} = {video_r, video_g, video_b};
assign MTL_DCLK = video_clk;
assign MTL_HSD = ~video_hs;
assign MTL_VSD = ~video_vs;

vga_pll vga_pll_inst(
	.areset(1'b0),
	.inclk0(CLOCK_50),
	.c0(video_clk),
	.locked(reset_n));

logic DataOut;
logic I2C_SCLK_old;
logic willread;
logic [7:0] cnt;

always_ff @(posedge CLOCK_50)
begin
	// Save the old clock state
	I2C_SCLK_old <= I2C_SCLK;

	// Init counter to 0
   if (G_SENSOR_CS_N) begin
		cnt <= 1'b0;
		willread <= 1'b0;
	end else if (~I2C_SCLK && I2C_SCLK_old && cnt == 8'd0) begin 
		willread <= DataOut;
		cnt <= cnt + 8'd1;
   end else if (~I2C_SCLK && I2C_SCLK_old) cnt <= cnt + 8'd1;
end

// Do not drive I2C_DAT if we are reading from it
assign I2C_SDAT = (cnt > 8) && willread ? 1'bz : DataOut ;

//=======================================================
//  Structural coding
//=======================================================

wire SDI1A;
assign PIC32_SDI1A = PIC32_CS_FPGA_N ? 1'bz : SDI1A;

 mtlsopc u0 (
	  .clk_clk                                 (CLOCK_50),
	  .reset_reset_n                           (PIC32_RST_FPGA_N),

	  .altpll_areset_conduit_export            (),
	  .altpll_locked_conduit_export            (),
	  .altpll_phasedone_conduit_export         (),

	  .altpll_sdram_clk                        (DRAM_CLK),
	  .sdram_wire_addr                         (DRAM_ADDR),
	  .sdram_wire_ba                           (DRAM_BA),
	  .sdram_wire_cas_n                        (DRAM_CAS_N),
	  .sdram_wire_cke                          (DRAM_CKE),
	  .sdram_wire_cs_n                         (DRAM_CS_N),
	  .sdram_wire_dq                           (DRAM_DQ),
	  .sdram_wire_dqm                          (DRAM_DQM),
	  .sdram_wire_ras_n                        (DRAM_RAS_N),
	  .sdram_wire_we_n                         (DRAM_WE_N),

	  .alt_vip_itc_clocked_video_vid_clk       (video_clk),
	  .alt_vip_itc_clocked_video_vid_data      ({8'b0, video_r, video_g, video_b}),
	  .alt_vip_itc_clocked_video_underflow     (),
	  .alt_vip_itc_clocked_video_vid_datavalid (),
	  .alt_vip_itc_clocked_video_vid_v_sync    (video_vs),
	  .alt_vip_itc_clocked_video_vid_h_sync    (video_hs),
	  .alt_vip_itc_clocked_video_vid_f         (),
	  .alt_vip_itc_clocked_video_vid_h         (),
	  .alt_vip_itc_clocked_video_vid_v         (),

	  .multi_touch_I2C_SDA                     (MTL_TOUCH_I2C_SDA),
     .multi_touch_I2C_SCL                     (MTL_TOUCH_I2C_SCL),
     .multi_touch_INT_n                       (MTL_TOUCH_INT_n),

     .pic32_MISO                              (SDI1A),
     .pic32_MOSI                              (PIC32_SDO1A),
     .pic32_SCK                               (PIC32_SCK1A),
     .pic32_CS_N                              (PIC32_CS_FPGA_N),
     .pic32_int2_export                       (PIC32_INT2),
	  .pic32_int1_export                       (PIC32_INT1),

	  .adxl345_MISO                            (I2C_SDAT),
     .adxl345_MOSI                            (DataOut),
     .adxl345_SCLK                            (I2C_SCLK),
     .adxl345_SS_n                            (G_SENSOR_CS_N),
	  
	  .flash_dclk                              (EPCS_DCLK),
     .flash_sce                               (EPCS_NCSO),
     .flash_sdo                               (EPCS_ASDO),
     .flash_data0                             (EPCS_DATA0)
	  
 );

 endmodule
