
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lt24hardware(

//////////// CLOCK //////////
input  logic        CLOCK_50,

//////////// LED //////////
output logic [7:0]  LED,

//////////// KEY //////////
input  logic [1:0]  KEY,

//////////// SW //////////
input  logic [3:0]  SW,

//////////// SDRAM ////////// 
output logic [12:0] DRAM_ADDR,
output logic [1:0]  DRAM_BA,
output logic        DRAM_CAS_N,
output logic        DRAM_CKE,
output logic        DRAM_CLK,
output logic        DRAM_CS_N,
inout  logic [15:0] DRAM_DQ,
output logic [1:0]  DRAM_DQM,
output logic        DRAM_RAS_N,
output logic        DRAM_WE_N,

//////////// Accelerometer //////////
output logic        G_SENSOR_CS_N,
input  logic        G_SENSOR_INT,
output logic        I2C_SCLK,
inout  logic        I2C_SDAT,

//////////// 2x13 GPIO Header //////////
input  logic        PIC32_SDO1A,
output logic        PIC32_SDI1A,
input  logic        PIC32_SCK1A,
input  logic        PIC32_CS_FPGA_N,
output logic        PIC32_INT1,
input  logic        PIC32_INT2,
 
input  logic        PIC32_C1TX,
output logic        PIC32_C1RX,
inout  logic        PIC32_SCL3A,
inout  logic        PIC32_SDA3A,
input  logic        PIC32_RST_FPGA_N,

inout  logic        PIC32_GPIO_211,
inout  logic        PIC32_GPIO_212,
input  logic        PIC32_GPIO_2_IN,
    
//////////////  LCD LT24 to GPIO1 ////////////////
output logic        LT24_ADC_CS_N,
output logic        LT24_ADC_DCLK,
output logic        LT24_ADC_DIN,
input  logic        LT24_ADC_BUSY,
input  logic        LT24_ADC_DOUT,
input  logic        LT24_ADC_PENIRQ_N,
output logic [15:0] LT24_D,
output logic        LT24_WR_N,
output logic        LT24_RD_N,
output logic        LT24_CS_N,
output logic        LT24_RESET_N,
output logic        LT24_RS,
output logic        LT24_LCD_ON
);

logic SDI1A;

assign PIC32_SDI1A = PIC32_CS_FPGA_N ? 1'bz : SDI1A;
assign LT24_LCD_ON = 1'b1;	 

lt24sopc u0 (
        // CLK/RESET
        .clk_clk                      (CLOCK_50), 
        .reset_reset_n                (PIC32_RST_FPGA_N),
          
        // PLL
        .pll_areset_conduit_export    (),
        .pll_locked_conduit_export    (),
        .pll_phasedone_conduit_export (),
		  
        // RAM
        .pll_sdram_clk                (DRAM_CLK),
        .sdram_wire_addr              (DRAM_ADDR),
        .sdram_wire_ba                (DRAM_BA),
        .sdram_wire_cas_n             (DRAM_CAS_N), 
        .sdram_wire_cke               (DRAM_CKE),
        .sdram_wire_cs_n              (DRAM_CS_N),
        .sdram_wire_dq                (DRAM_DQ),
        .sdram_wire_dqm               (DRAM_DQM),
        .sdram_wire_ras_n             (DRAM_RAS_N), 
        .sdram_wire_we_n              (DRAM_WE_N),
		  
        // LCD
        .lcd_cs                       (LT24_CS_N), 
        .lcd_rs                       (LT24_RS),
        .lcd_rd                       (LT24_RD_N),
        .lcd_wr                       (LT24_WR_N),
        .lcd_data                     (LT24_D), 
        .lcd_reset_n_export           (LT24_RESET_N),
		  
        // Touch panel
        .touch_MISO                   (LT24_ADC_DOUT),
        .touch_MOSI                   (LT24_ADC_DIN),
        .touch_SCLK                   (LT24_ADC_DCLK),
        .touch_SS_n                   (LT24_ADC_CS_N),
        .touch_pen_irq_n_export       (LT24_ADC_PENIRQ_N),
        .touch_busy_export            (LT24_ADC_BUSY),
        
        // PIC32
        .pic32_MISO                   (SDI1A),
        .pic32_MOSI                   (PIC32_SDO1A),
        .pic32_SCK                    (PIC32_SCK1A),
        .pic32_CS_N                   (PIC32_CS_FPGA_N),
        .pic32_int2_export            (PIC32_INT2),
        .pic32_int1_export            (PIC32_INT1)
    );
	 
endmodule
